'use client';

import React from 'react';
import { Award, CheckCircle2, ShieldCheck, Sparkles, ExternalLink, Cpu } from 'lucide-react';

interface AttestationCardProps {
  isAttested: boolean;
  attestationId?: string;
  txHash?: string;
  artifactHash?: string;
  policyHash?: string;
  verificationCount?: number;
}

export function AttestationCard({
  isAttested,
  attestationId = '0x8fa72109841bcefa019283746152431289471928374615243128947192837461',
  txHash = '0x3b21908471239084712098347102938471029384710293847102938471029384',
  artifactHash = '0x91faa72c18d84b067a840e11892fc0b418a0902827164b38d011749102837461',
  policyHash = '0x4f8a3b21c990fe017654ba3210ef89a72c41890e7612f00a9d8e123456789abc',
  verificationCount = 1
}: AttestationCardProps) {
  return (
    <div className={`rounded-2xl border p-6 transition-all ${
      isAttested
        ? 'border-indigo-500/80 bg-gradient-to-br from-midnight-900 to-indigo-950/40 glow-box'
        : 'border-slate-800 bg-midnight-900/60 opacity-60'
    }`}>
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Award className={`w-5 h-5 ${isAttested ? 'text-indigo-400' : 'text-slate-500'}`} />
          <h4 className="font-semibold text-white">Midnight ZK Attestation</h4>
        </div>
        {isAttested ? (
          <span className="flex items-center gap-1.5 text-xs font-bold px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/50">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            ON-CHAIN VERIFIED
          </span>
        ) : (
          <span className="text-xs text-slate-500 font-mono">AWAITING PROOF</span>
        )}
      </div>

      {isAttested ? (
        <div className="space-y-3">
          <div className="p-3.5 rounded-xl bg-slate-950/70 border border-indigo-900/40 space-y-2 text-xs">
            <div>
              <span className="text-slate-400">Attestation ID:</span>
              <div className="font-mono text-indigo-300 truncate mt-0.5" title={attestationId}>
                {attestationId}
              </div>
            </div>
            <div>
              <span className="text-slate-400">Transaction Hash:</span>
              <div className="font-mono text-indigo-300 truncate mt-0.5" title={txHash}>
                {txHash}
              </div>
            </div>
            <div className="flex items-center justify-between pt-1 border-t border-slate-800/80 text-[11px]">
              <span className="text-slate-400">Total Contract Verifications:</span>
              <span className="font-bold text-emerald-400 font-mono">#{verificationCount}</span>
            </div>
          </div>

          <div className="p-3 rounded-lg bg-indigo-950/30 border border-indigo-800/40 text-xs text-slate-300 flex items-start gap-2">
            <Cpu className="w-4 h-4 text-indigo-400 shrink-0 mt-0.5" />
            <span>
              Zero-knowledge proof generated by local Midnight Proof Server. Verified by Compact contract circuit without revealing repository contents.
            </span>
          </div>
        </div>
      ) : (
        <div className="py-8 text-center text-xs text-slate-500">
          Run local safety scan and attest clean repository to generate cryptographic ZK proof.
        </div>
      )}
    </div>
  );
}
